# Configuración para GitHub Pages - Santander QA Dashboard
title: "Santander QA Dashboard"
description: "Sistema de monitoreo y reporte de pruebas de calidad para equipos de desarrollo"
url: "https://aariverar.github.io"
baseurl: "/reporte_diario_qa"

# Configuración del sitio
author: "Abraham Rivera - Equipo QA Santander"
email: "arivera_scb@santander.com.pe"

# Configuración de GitHub Pages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuración de archivos
include:
  - "_*"
  - ".nojekyll"

exclude:
  - "node_modules/"
  - "*.log"
  - ".git/"
  - ".github/"
  - "Gemfile*"

# Configuración de markdown
markdown: kramdown
highlighter: rouge

# Configuración de colecciones (si es necesario en el futuro)
collections_dir: collections

# SEO y metadatos
lang: es
timezone: America/Lima

# Configuración de navegación (para posibles extensiones futuras)
navigation:
  - title: "Dashboard"
    url: "/"
  - title: "Documentación"
    url: "/README.html"